#pragma once

SMC_DECLARE_INTERFACE(IARPTableEntry, {79624D6F-491D-4285-8988-C08FA256E371})
	: public ISMCInterface
{
public:
	STDMETHOD_(LPCWSTR, GetIPAddrStr)() PURE;
	STDMETHOD_(UINT32, GetIPAddr)() PURE;

	STDMETHOD_(LPCWSTR, GetMACAddrStr)() PURE;
	STDMETHOD_(UINT64, GetMACAddr)() PURE;

	STDMETHOD_(BOOL, SetIPAddr)(LPCWSTR pIPAddrStr) PURE;
	STDMETHOD_(BOOL, SetIPAddr)(UINT32 nIPAddr) PURE;

	STDMETHOD_(BOOL, SetMACAddr)(LPCWSTR pMACAddrStr) PURE;
	STDMETHOD_(BOOL, SetMACAddr)(UINT64 nMACAddr) PURE;
};