#pragma once

SMC_DECLARE_INTERFACE(IMACTableEntry, {79B1D932-A4B6-4324-9E36-514854C3D30E})
	: public ISMCInterface
{
public:
	STDMETHOD_(LPCWSTR, GetMACAddrStr)() PURE;
	STDMETHOD_(UINT64, GetMACAddr)() PURE;

	STDMETHOD_(BOOL, SetMACAddr)(LPCWSTR pMACAddrStr) PURE;
	STDMETHOD_(BOOL, SetMACAddr)(UINT64 nMACAddr) PURE;

	STDMETHOD_(BOOL, SetPortID)(UINT32 nPortId) PURE;

	STDMETHOD_(UINT32, GetPortID)() PURE;
};